services:
  db:
    image: postgres:16
    container_name: pwnchat-project-db-1
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: pwnbuffer_chat
    ports:
      - "5432:5432" # publish to host so DBeaver and host-backend can connect
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d pwnbuffer_chat"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
